/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lamborghini;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author RishiRAJ
 */
public class rishidesign extends javax.swing.JFrame {

    /**
     * Creates new form rishidesign
     */
    public rishidesign() {
        initComponents();
        fillEmp();
    }
    void fillEmp(){
    try{
        c1.removeAllItems();
        Class.forName("com.mysql.jdbc.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
        Statement s=c.createStatement();
        ResultSet r=s.executeQuery("select*from rishi");
        while(r.next()){
            c1.addItem(r.getInt(1)+"");
            
        }
    }catch(Exception e){
        System.out.println("Error"+e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jint1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jint2 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        e4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        e6 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        e8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jint3 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jint4 = new javax.swing.JInternalFrame();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JPasswordField();
        jint5 = new javax.swing.JInternalFrame();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jint6 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        jint1.setClosable(true);
        jint1.setIconifiable(true);
        jint1.setMaximizable(true);
        jint1.setResizable(true);
        jint1.setMaximumSize(new java.awt.Dimension(500, 500));
        jint1.setMinimumSize(new java.awt.Dimension(500, 500));
        jint1.setPreferredSize(new java.awt.Dimension(500, 500));
        jint1.setVisible(false);
        jint1.getContentPane().setLayout(null);

        jLabel1.setText("S.No:");
        jint1.getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 90, 20);

        jLabel2.setText("Model no:");
        jint1.getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 100, 20);

        jLabel3.setText("Customer Name:");
        jint1.getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 110, 20);

        jLabel4.setText("Model:");
        jint1.getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 100, 20);

        jLabel5.setText("Price:");
        jint1.getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 90, 20);

        jLabel6.setText("Visit date:");
        jint1.getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 100, 20);

        jLabel7.setText("City:");
        jint1.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 260, 70, 20);

        jLabel8.setText("State:");
        jint1.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 300, 90, 20);

        jLabel9.setText("Contact No:");
        jint1.getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 340, 90, 20);
        jint1.getContentPane().add(t1);
        t1.setBounds(160, 10, 180, 30);
        jint1.getContentPane().add(t2);
        t2.setBounds(160, 50, 180, 30);
        jint1.getContentPane().add(t3);
        t3.setBounds(160, 90, 180, 30);
        jint1.getContentPane().add(t4);
        t4.setBounds(160, 130, 180, 30);
        jint1.getContentPane().add(t5);
        t5.setBounds(160, 170, 180, 30);
        jint1.getContentPane().add(t6);
        t6.setBounds(160, 210, 180, 30);
        jint1.getContentPane().add(t7);
        t7.setBounds(160, 250, 180, 30);
        jint1.getContentPane().add(t8);
        t8.setBounds(160, 290, 180, 30);

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jint1.getContentPane().add(t9);
        t9.setBounds(160, 330, 180, 30);

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jint1.getContentPane().add(jButton1);
        jButton1.setBounds(160, 400, 61, 23);

        getContentPane().add(jint1);
        jint1.setBounds(450, 0, 500, 500);

        jint2.setClosable(true);
        jint2.setIconifiable(true);
        jint2.setMaximizable(true);
        jint2.setResizable(true);
        jint2.setMaximumSize(new java.awt.Dimension(500, 500));
        jint2.setMinimumSize(new java.awt.Dimension(500, 500));
        jint2.setPreferredSize(new java.awt.Dimension(500, 500));
        jint2.setVisible(false);
        jint2.getContentPane().setLayout(null);

        jLabel10.setText("S_no:");
        jint2.getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 20, 130, 30);

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jint2.getContentPane().add(c1);
        c1.setBounds(210, 20, 200, 30);

        jLabel11.setText("model_no:");
        jint2.getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 60, 160, 30);

        jLabel12.setText("Customer_Name:");
        jint2.getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 100, 130, 30);

        jLabel13.setText("Model:");
        jint2.getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 140, 110, 30);

        jLabel14.setText("Price:");
        jint2.getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 180, 120, 30);

        jLabel15.setText("Visit_date:");
        jint2.getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 220, 110, 30);

        jLabel16.setText("City:");
        jint2.getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 260, 120, 30);

        jLabel17.setText("State:");
        jint2.getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 300, 110, 30);

        jLabel18.setText("Contact_no:");
        jint2.getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 340, 130, 30);
        jint2.getContentPane().add(e1);
        e1.setBounds(210, 60, 200, 30);
        jint2.getContentPane().add(e2);
        e2.setBounds(210, 100, 200, 30);
        jint2.getContentPane().add(e3);
        e3.setBounds(210, 140, 200, 30);
        jint2.getContentPane().add(e4);
        e4.setBounds(210, 180, 200, 30);
        jint2.getContentPane().add(e5);
        e5.setBounds(210, 220, 200, 30);
        jint2.getContentPane().add(e6);
        e6.setBounds(210, 260, 200, 30);
        jint2.getContentPane().add(e7);
        e7.setBounds(210, 300, 200, 30);
        jint2.getContentPane().add(e8);
        e8.setBounds(210, 340, 200, 30);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jint2.getContentPane().add(jButton2);
        jButton2.setBounds(210, 420, 90, 30);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jint2.getContentPane().add(jButton3);
        jButton3.setBounds(330, 420, 80, 30);

        getContentPane().add(jint2);
        jint2.setBounds(0, 0, 500, 500);

        jint3.setClosable(true);
        jint3.setIconifiable(true);
        jint3.setMaximizable(true);
        jint3.setResizable(true);
        jint3.setMaximumSize(new java.awt.Dimension(900, 550));
        jint3.setMinimumSize(new java.awt.Dimension(900, 550));
        jint3.setVisible(false);
        jint3.getContentPane().setLayout(null);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S_no", "Model_no", "Customer_name", "Model", "Price", "Visit_date", "City", "State", "Contact_no"
            }
        ));
        tab.setMaximumSize(new java.awt.Dimension(850, 500));
        tab.setMinimumSize(new java.awt.Dimension(850, 500));
        tab.setPreferredSize(new java.awt.Dimension(850, 500));
        jScrollPane1.setViewportView(tab);

        jint3.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 900, 330);

        jLabel19.setText("Search Entry:");
        jint3.getContentPane().add(jLabel19);
        jLabel19.setBounds(150, 360, 80, 30);
        jint3.getContentPane().add(text1);
        text1.setBounds(250, 360, 180, 30);

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jint3.getContentPane().add(jButton4);
        jButton4.setBounds(450, 360, 190, 30);

        getContentPane().add(jint3);
        jint3.setBounds(10, 11, 940, 460);

        jint4.setClosable(true);
        jint4.setIconifiable(true);
        jint4.setMaximizable(true);
        jint4.setMaximumSize(new java.awt.Dimension(450, 450));
        jint4.setMinimumSize(new java.awt.Dimension(450, 450));
        jint4.setPreferredSize(new java.awt.Dimension(450, 450));
        jint4.setVisible(false);
        jint4.getContentPane().setLayout(null);

        jLabel21.setText("Employee Id:");
        jint4.getContentPane().add(jLabel21);
        jLabel21.setBounds(60, 30, 80, 20);

        jLabel24.setText("Name:");
        jint4.getContentPane().add(jLabel24);
        jLabel24.setBounds(60, 70, 60, 20);

        jLabel25.setText("E_Mail Id:");
        jint4.getContentPane().add(jLabel25);
        jLabel25.setBounds(60, 120, 70, 20);

        jLabel26.setText("Set User Name:");
        jint4.getContentPane().add(jLabel26);
        jLabel26.setBounds(60, 170, 90, 30);

        jLabel27.setText("Set Password:");
        jint4.getContentPane().add(jLabel27);
        jLabel27.setBounds(60, 220, 80, 20);

        jButton5.setText("Sign Up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jint4.getContentPane().add(jButton5);
        jButton5.setBounds(180, 300, 100, 30);
        jint4.getContentPane().add(r1);
        r1.setBounds(210, 20, 140, 30);
        jint4.getContentPane().add(r2);
        r2.setBounds(210, 60, 140, 30);
        jint4.getContentPane().add(r3);
        r3.setBounds(210, 110, 140, 30);
        jint4.getContentPane().add(r4);
        r4.setBounds(210, 160, 140, 30);
        jint4.getContentPane().add(r5);
        r5.setBounds(210, 210, 140, 30);

        getContentPane().add(jint4);
        jint4.setBounds(500, 0, 450, 450);

        jint5.setClosable(true);
        jint5.setIconifiable(true);
        jint5.setMaximizable(true);
        jint5.setResizable(true);
        jint5.setMaximumSize(new java.awt.Dimension(450, 450));
        jint5.setMinimumSize(new java.awt.Dimension(450, 450));
        jint5.setPreferredSize(new java.awt.Dimension(450, 450));
        jint5.setVisible(false);
        jint5.getContentPane().setLayout(null);

        jLabel20.setText("UserName:");
        jint5.getContentPane().add(jLabel20);
        jLabel20.setBounds(80, 60, 90, 30);

        jLabel22.setText("Password:");
        jint5.getContentPane().add(jLabel22);
        jLabel22.setBounds(80, 120, 100, 40);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jint5.getContentPane().add(user);
        user.setBounds(200, 60, 160, 40);
        jint5.getContentPane().add(upass);
        upass.setBounds(200, 120, 160, 40);

        jButton6.setText("Sign In");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jint5.getContentPane().add(jButton6);
        jButton6.setBounds(250, 190, 100, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log In"));
        jint5.getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 370, 230);

        jButton7.setText("Sign UP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jint5.getContentPane().add(jButton7);
        jButton7.setBounds(250, 320, 150, 40);

        getContentPane().add(jint5);
        jint5.setBounds(0, 0, 450, 450);

        jint6.setClosable(true);
        jint6.setIconifiable(true);
        jint6.setMaximizable(true);
        jint6.setResizable(true);
        jint6.setMaximumSize(new java.awt.Dimension(500, 500));
        jint6.setMinimumSize(new java.awt.Dimension(500, 500));
        jint6.setPreferredSize(new java.awt.Dimension(500, 500));
        jint6.setVisible(false);
        jint6.getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("WELCOME TO LAMBORGHINI MUMBAI..\n\nWHERE TO FIND US\n\nLamborghini Mumbai\n\nGround Floor,Rajan House,Appasaheb Marathe\n\n\nMarg,Prabhadevi\n\n400 025 Mumbai\n\nPhone:+91 22 6612 3888");
        jTextArea1.setMaximumSize(new java.awt.Dimension(400, 600));
        jTextArea1.setMinimumSize(new java.awt.Dimension(400, 600));
        jTextArea1.setName(""); // NOI18N
        jTextArea1.setPreferredSize(new java.awt.Dimension(400, 600));
        jScrollPane2.setViewportView(jTextArea1);

        jint6.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 480, 360);

        getContentPane().add(jint6);
        jint6.setBounds(0, 0, 470, 390);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\RishiRAJ\\Desktop\\Lamborghini-Logo-Wallpaper 2.jpg")); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.setMaximumSize(new java.awt.Dimension(1000, 600));
        jLabel23.setMinimumSize(new java.awt.Dimension(1000, 600));
        jLabel23.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 1000, 600);

        jMenu2.setText("Home            ");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Log in");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Insert data                    ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Insert");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Update&Delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tables                     ");

        jMenuItem5.setText("Customer's Information");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Contact Us      ");

        jMenuItem2.setText("Lamborghini");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void insert(){
        if(t1.getText().trim().length()==0 || t2.getText().trim().length()==0 || t3.getText().trim().length()==0 || t4.getText().trim().length()==0 || t5.getText().trim().length()==0 || t6.getText().trim().length()==0 || t7.getText().trim().length()==0 || t8.getText().trim().length()==0 || t9.getText().trim().length()==0)
         {
            javax.swing.JOptionPane.showMessageDialog(this,"Please insert data");
        }else if(t9.getText().trim().length()>10 || t9.getText().trim().length()<10 ){
            javax.swing.JOptionPane.showMessageDialog(this, "Please insert a valid Contact No");
    }else{
       
         try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            int q1=Integer.parseInt(t1.getText().trim());
            String q2=t2.getText().trim();
            String q3=t3.getText().trim();
            String q4=t4.getText().trim();
            String q5=t5.getText().trim();
            String q6=t6.getText().trim();
            String q7=t7.getText().trim();
            String q8=t8.getText().trim();
            long q9= Long.parseLong(t9.getText().trim());
            
            int i=s.executeUpdate("insert into rishi values("+q1+",'"+q2+"','"+q3+"','"+q4+"','"+q5+"','"+q6+"','"+q7+"','"+q8+"',"+q9+")");
            
            
            if(i>0){
                
                javax.swing.JOptionPane.showMessageDialog(this,"Data Inserted");
                fillEmp();
                t1.setText("");
                t2.setText("");
                t3.setText("");
                t4.setText("");
                t5.setText("");
                t6.setText("");
                t7.setText("");
                t8.setText("");
                t9.setText("");
                
                
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,"Data not inserted");
            }
        }catch(Exception e){
            System.out.println(e);
        }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            int i=Integer.parseInt(c1.getSelectedItem().toString().trim());
            ResultSet r=s.executeQuery("select*from rishi where s_no="+i);
            if(r.next()){
                e1.setText(r.getString(2));
                e2.setText(r.getString(3));
                e3.setText(r.getString(4));
                e4.setText(r.getString(5));
                e5.setText(r.getString(6));
                e6.setText(r.getString(7));
                e7.setText(r.getString(8));
                e8.setText(r.getLong(9)+"");
                
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      int ii=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure? ");
      if(ii==0){
         
            try{
                int q1=Integer.parseInt(c1.getSelectedItem().toString().trim());
                String q2=e1.getText().trim();
                String q3=e2.getText().trim();
                String q4=e3.getText().trim();
                String q5=e4.getText().trim();
                String q6=e5.getText().trim();
                String q7=e6.getText().trim();
                String q8=e7.getText().trim();
                long q9=Long.parseLong(e8.getText().trim());
                Class.forName("com.mysql.jdbc.Driver");
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
                PreparedStatement s=c.prepareStatement("update rishi set model_no=?,customer_name=?,model=?,price=?,visit_date=?,city=?,state=?,contact_no=? where s_no=?");
                s.setString(1,q2);s.setString(2,q3);s.setString(3,q4);s.setString(4,q5);s.setString(5,q6);s.setString(6, q7);s.setString(7, q8);s.setLong(8,q9); s.setInt(9, q1);
                int i=s.executeUpdate();
                if(i>0){
                    
                    javax.swing.JOptionPane.showMessageDialog(this,"Data Updated");
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this,"Data Not updated");
                }
            }
            catch(Exception e){
                System.out.println(e);
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ii=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure? ");
      if(ii==0){
        try{
            int q1=Integer.parseInt(c1.getSelectedItem().toString().trim());
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            PreparedStatement s=c.prepareStatement("delete from rishi where s_no=?");
            s.setInt(1,q1);
            int i=s.executeUpdate();
            if(i>0){
                javax.swing.JOptionPane.showMessageDialog(this,"Data deleted");
             //   allEmp();
                e1.setText("");
                e2.setText("");
                e3.setText("");
                e4.setText("");
                e5.setText("");
                e6.setText("");
                e7.setText("");
                fillEmp();
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,"Data Not deleted");
            }
        }
            catch(Exception e){
                System.out.println(e);
                    
                    }
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            javax.swing.table.DefaultTableModel d=(javax.swing.table.DefaultTableModel)tab.getModel();
            d.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select * from rishi where Customer_name like '%"+text1.getText().trim()+"%'");
            while(r.next()){
                String S_no=r.getInt(1)+"";
                String Model_no=r.getString(2);
                String Customer_name=r.getString(3);
                String Model=r.getString(4);
                String Price=r.getString(5);
                String Visit_date=r.getString(6);
                String City=r.getString(7);
                String State=r.getString(8);
                String Contact_no=r.getLong(9)+"";
               
                d.addRow(new String[]{S_no,Model_no,Customer_name,Model,Price,Visit_date,City,State,Contact_no});
                
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
     
    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
        insert();        
      
    }//GEN-LAST:event_t9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         jint1.setVisible(false);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select count(s_no) from rishi");
            r.next();
            int i=r.getInt(1);
            t1.setText(i+"");
        }catch(Exception e){
            System.out.println(e);
        }
        
   //jint3.setVisible(true);
     //   try{
       //     javax.swing.table.DefaultTableModel d=(javax.swing.table.DefaultTableModel)tab.getModel();
         //   d.setRowCount(0);
           // Class.forName("com.mysql.jdbc.Driver");
        //    Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
          //  Statement s=c.createStatement();
          //  ResultSet r=s.executeQuery("select * from rishi");
        //    while(r.next()){
            //    String S_no=r.getInt(1)+"";
              //  String Model_no=r.getString(2);
                //String Customer_name=r.getString(3);
               // String Model=r.getString(4);
      //          String Price=r.getString(5);
    //            String Visit_date=r.getString(6);
  //              String City=r.getString(7);
//                String State=r.getString(8);
              //  String Contact_no=r.getLong(9)+"";
               
            //    d.addRow(new String[]{S_no,Model_no,Customer_name,Model,Price,Visit_date,City,State,Contact_no});
          //  }
        //}catch(Exception e){
         //   System.out.println(e);
       // }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jint5.setVisible(true);
        
       // jint1.setVisible(true);
        //try{
          //  Class.forName("com.mysql.jdbc.Driver");
           // java.sql.Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            //Statement s=c.createStatement();
            //ResultSet r=s.executeQuery("select count(s_no) from rishi");
          //  r.next();
           // int i=r.getInt(1);
           // t1.setText(i+"");
        //}catch(Exception e){
          //  System.out.println(e);
        //}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            int k1=Integer.parseInt(r1.getText().trim());
            String k2=r2.getText().trim();
            ResultSet r=s.executeQuery("select * from rishi where s_no='"+k1+"' and customer_name='"+k2+"'");
            if(r.next()){
                int q1=Integer.parseInt(r1.getText().trim());
                String q2=r2.getText().trim();
                String q3=r3.getText().trim();
                String q4=r4.getText().trim();
                String q5=r5.getText().trim();
                int i=s.executeUpdate("insert into signup values("+q1+",'"+q2+"','"+q3+"','"+q4+"','"+q5+"')");
                javax.swing.JOptionPane.showMessageDialog(this, "Signup successfull");
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,"Incorrect id or Name");
               
                
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         jint3.setVisible(true);
        try{
            javax.swing.table.DefaultTableModel d=(javax.swing.table.DefaultTableModel)tab.getModel();
            d.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select * from rishi");
            while(r.next()){
                String S_no=r.getInt(1)+"";
                String Model_no=r.getString(2);
                String Customer_name=r.getString(3);
                String Model=r.getString(4);
                String Price=r.getString(5);
                String Visit_date=r.getString(6);
                String City=r.getString(7);
                String State=r.getString(8);
                String Contact_no=r.getLong(9)+"";
               
                d.addRow(new String[]{S_no,Model_no,Customer_name,Model,Price,Visit_date,City,State,Contact_no});
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jint4.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         jint2.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
      void done(){ 
          jint5.setVisible(true);
          try{
              Class.forName("com.mysql.jdbc.Driver");
              java.sql.Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/lamborghini","root","root");
              Statement s=c.createStatement();
              String k1=user.getText();
              String k2=upass.getText();
              ResultSet r=s.executeQuery("Select * from signup where Name='"+k1+"' and Password='"+k2+"'");
              if(r.next()){
                  jint1.setVisible(true);
                  
                 // jint2.setVisible(true);
                 // jint3.setVisible(true);
              }else{
                  javax.swing.JOptionPane.showMessageDialog(this,"Incorrect username or password");
                           
              }
           }catch(Exception e){
                      System.out.println(e);
                      }
}
          
                  
      
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        done();
        user.setText("");
        upass.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jint6.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rishidesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rishidesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rishidesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rishidesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rishidesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JTextField e8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JInternalFrame jint1;
    private javax.swing.JInternalFrame jint2;
    private javax.swing.JInternalFrame jint3;
    private javax.swing.JInternalFrame jint4;
    private javax.swing.JInternalFrame jint5;
    private javax.swing.JInternalFrame jint6;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JPasswordField r5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTable tab;
    private javax.swing.JTextField text1;
    private javax.swing.JPasswordField upass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private void allEmp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
